<?php
// $Id: xoops_version.php 15 2007-02-15 16:11:16Z BitC3R0 $
// --------------------------------------------------------
// RMSOFT MiniShop
// Módulo para el manejo de catálogos en línea
// CopyRight © 2005 - 2006. Red México Soft
// Autor: BitC3R0
// http://www.redmexico.com.mx
// http://www.xoopsmexico.net
// --------------------------------------------------------
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public
// License along with this program; if not, write to the Free
// Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
// MA 02111-1307 USA
// --------------------------------------------------------
// @copyright: 2006 - 2007 Red México Soft
// $Author: BitC3R0 $
// @package: RMSOFT MiniShop

$modversion['name'] = "RMSOFT MiniShop";
$modversion['version'] = "1.3";
$modversion['description'] = "Catálogo de Productos en Línea";
$modversion['author'] = "BitC3R0";
$modversion['credits'] = "Red México Soft <http://www.redmexico.com.mx>";
$modversion['help'] = "";
$modversion['license'] = "See GPL License";
$modversion['official'] = 0;
$modversion['image'] = "images/logo.png";
$modversion['dirname'] = "rmms";
$modversion['iconbig'] = "images/iconbig.png";
$modversion['iconsmall'] = "images/iconsmall.png";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "rmms_productos";
$modversion['tables'][1] = "rmms_categos";
$modversion['tables'][2] = "rmms_images";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['hasMain'] = 1;

// Bloques
$modversion['blocks'][1]['file'] = "rmms_bmenu.php";
$modversion['blocks'][1]['name'] = "Menu del Catálogo";
$modversion['blocks'][1]['description'] = '';
$modversion['blocks'][1]['show_func'] = "b_rmms_show_menu";
$modversion['blocks'][1]['template'] = 'rmms_bmenu.html';

$modversion['blocks'][2]['file'] = "rmms_brecents.php";
$modversion['blocks'][2]['name'] = "Productos Recientes";
$modversion['blocks'][2]['description'] = '';
$modversion['blocks'][2]['show_func'] = "b_rmms_show_recents";
$modversion['blocks'][2]['edit_func'] = "b_rmms_recents_edit";
$modversion['blocks'][2]['options'] = "5";
$modversion['blocks'][2]['template'] = 'rmms_brecents.html';

$modversion['blocks'][3]['file'] = "rmms_brandom.php";
$modversion['blocks'][3]['name'] = "Productos";
$modversion['blocks'][3]['description'] = '';
$modversion['blocks'][3]['show_func'] = "b_rmms_show_random";
$modversion['blocks'][3]['template'] = 'rmms_brandom.html';

// Templates
$modversion['templates'][1]['file'] = 'rmms_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'rmms_categos.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'rmms_productos.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'rmms_search.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'rmms_moreinfo.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'rmms_prod.html';
$modversion['templates'][6]['description'] = '';


// Tipo de editor
$modversion['config'][0]['name'] = 'editor';
$modversion['config'][0]['title'] = '_MI_RMMS_EDITOR';
$modversion['config'][0]['description'] = '';
$modversion['config'][0]['formtype'] = 'select';
$modversion['config'][0]['valuetype'] = 'text';
$modversion['config'][0]['default'] = 'tiny';
$modversion['config'][0]['options'] = array(
											_MI_RMMS_FORM_DHTML=>'dhtml',
											_MI_RMMS_FORM_COMPACT=>'textarea',
											_MI_RMMS_FORM_TINY=>'tiny',
											_MI_RMMS_FORM_HTMLAREA=>'htmlarea',
											_MI_RMMS_FORM_FCK=>'fckeditor'
											);


// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'modtitle';

// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_MI_MODTITLE';

// description of this config option displayed under title
$modversion['config'][1]['description'] = '_MI_MODTITLEDESC';

// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'textbox';

// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][1]['valuetype'] = 'text';

// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = "RMSOFT MiniShop";

// options to be displayed in selection box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values

// Productos Recientes
$modversion['config'][2]['name'] = 'recientes';
$modversion['config'][2]['title'] = '_MI_RECIENTES';
$modversion['config'][2]['description'] = '_MI_RECIENTESDESC';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 5;

//Configurar ancho de las imágenes
$modversion['config'][3]['name'] = 'imgcategow';
$modversion['config'][3]['title'] = '_MI_IMGCATEGOW';
$modversion['config'][3]['description'] = '';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = "100";

//Numero de columnas para los productos
$modversion['config'][4]['name'] = 'cols';
$modversion['config'][4]['title'] = '_MI_RMMS_COLS';
$modversion['config'][4]['description'] = '';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = "4";

//Numero de columnas para los productos
$modversion['config'][5]['name'] = 'categocols';
$modversion['config'][5]['title'] = '_MI_RMMS_CATEGOCOLS';
$modversion['config'][5]['description'] = '';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = "3";

//Formato de la Moneda
$modversion['config'][6]['name'] = 'curformat';
$modversion['config'][6]['title'] = '_MI_RMMS_CURFORMAT';
$modversion['config'][6]['description'] = '';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'text';
$modversion['config'][6]['default'] = "$ %s";

// Lugares decimales para los precios
$modversion['config'][7]['name'] = 'decimales';
$modversion['config'][7]['title'] = '_MI_RMMS_DECIMALS';
$modversion['config'][7]['description'] = '';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 2;

// Lugares decimales para los precios
$modversion['config'][8]['name'] = 'decsep';
$modversion['config'][8]['title'] = '_MI_RMMS_DECSEP';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'text';
$modversion['config'][8]['default'] = ".";

// Lugares decimales para los precios
$modversion['config'][9]['name'] = 'milsep';
$modversion['config'][9]['title'] = '_MI_RMMS_MILSEP';
$modversion['config'][9]['description'] = '';
$modversion['config'][9]['formtype'] = 'textbox';
$modversion['config'][9]['valuetype'] = 'text';
$modversion['config'][9]['default'] = ",";

// Lugares decimales para los precios
$modversion['config'][10]['name'] = 'formatpeso';
$modversion['config'][10]['title'] = '_MI_RMMS_PESO';
$modversion['config'][10]['description'] = '';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = "%s kgs";

// Email para recibir información
$modversion['config'][11]['name'] = 'infoemail';
$modversion['config'][11]['title'] = '_MI_RMMS_MAIL';
$modversion['config'][11]['description'] = '';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'text';
$modversion['config'][11]['default'] = '';

// Medidas de las imágenes de productos
$modversion['config'][12]['name'] = 'thwidth';
$modversion['config'][12]['title'] = '_MI_RMMS_THWIDTH';
$modversion['config'][12]['description'] = '';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = '80';

$modversion['config'][13]['name'] = 'thheight';
$modversion['config'][13]['title'] = '_MI_RMMS_THHEIGHT';
$modversion['config'][13]['description'] = '';
$modversion['config'][13]['formtype'] = 'textbox';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = '80';

$modversion['config'][14]['name'] = 'imgwidth';
$modversion['config'][14]['title'] = '_MI_RMMS_IMGWIDTH';
$modversion['config'][14]['description'] = '';
$modversion['config'][14]['formtype'] = 'textbox';
$modversion['config'][14]['valuetype'] = 'int';
$modversion['config'][14]['default'] = '400';

$modversion['config'][15]['name'] = 'imgheight';
$modversion['config'][15]['title'] = '_MI_RMMS_IMGHEIGHT';
$modversion['config'][15]['description'] = '';
$modversion['config'][15]['formtype'] = 'textbox';
$modversion['config'][15]['valuetype'] = 'int';
$modversion['config'][15]['default'] = '400';

// Mostrar precios a usuarios anónimos
$modversion['config'][16]['name'] = 'show_price';
$modversion['config'][16]['title'] = '_MI_RMMS_SHOWPRICE';
$modversion['config'][16]['description'] = '';
$modversion['config'][16]['formtype'] = 'yesno';
$modversion['config'][16]['valuetype'] = 'int';
$modversion['config'][16]['default'] = 0;

// Leyenda de impuestos
$modversion['config'][17]['name'] = 'taxincluded';
$modversion['config'][17]['title'] = '_MI_RMMS_TAXLEGEND';
$modversion['config'][17]['description'] = '';
$modversion['config'][17]['formtype'] = 'yesno';
$modversion['config'][17]['valuetype'] = 'int';
$modversion['config'][17]['default'] = 1;

// Mostrar imágenes de Categorías
$modversion['config'][18]['name'] = 'showcategoimages';
$modversion['config'][18]['title'] = '_MI_RMMS_SHOWCATIMG';
$modversion['config'][18]['description'] = '';
$modversion['config'][18]['formtype'] = 'yesno';
$modversion['config'][18]['valuetype'] = 'int';
$modversion['config'][18]['default'] = 0;

// Tamaño de archivo
$modversion['config'][19]['name'] = 'maxfilesize';
$modversion['config'][19]['title'] = '_MI_RMMS_MAXSIZE';
$modversion['config'][19]['description'] = '';
$modversion['config'][19]['formtype'] = 'textbox';
$modversion['config'][19]['valuetype'] = 'int';
$modversion['config'][19]['default'] = 1;

// Unidad de Conversión
$modversion['config'][20]['name'] = 'sizeunit';
$modversion['config'][20]['title'] = '_MI_RMMS_MAXUNIT';
$modversion['config'][20]['description'] = '';
$modversion['config'][20]['formtype'] = 'select';
$modversion['config'][20]['valuetype'] = 'int';
$modversion['config'][20]['default'] = 3;
$modversion['config'][20]['options'] = array(_MI_RMMS_MB=>3,_MI_RMMS_KB=>2,_MI_RMMS_BY=>1);
?>
